myshell: myshell.o
	@echo "Building 'myshell'..."
	@gcc -o myshell myshell.o

myshell.o: myshell.c
	@echo "Building 'myshell.o'..."
	@gcc -c myshell.c

clean:
	@echo "Cleaning up built files..."
	@rm -f myshell myshell.o
